### ISSUE TITLE
`stripe.Charge` either not installed, or is abstract.

### ISSUE THREAD

**Issue by elena** [thecut/thecut-stripe#1]
`./manage.py check` is now returning the following error:

```
CommandError: System check identified some issues:

ERRORS:
jobs.Job.payment: (fields.E300) Field defines a relation with model 'stripe.Charge', which is either not installed, or is abstract.
```

Model: https://bitbucket.org/elequ/jobs.diversity/commits/38fa1b4a7476833c6f86a13d9ef337b3333ba98d#Ljobs/models.pyT119

Following migrates/syncs OK:

```
_stripe_customer = models.OneToOneField(
    'stripe.Customer', related_name='job', blank=True, null=True,
    editable=False, on_delete=models.SET_NULL)
```

Not OK:

```
payment = models.OneToOneField('stripe.Charge', related_name='job',
                               blank=True, null=True, editable=False,
                               on_delete=models.SET_NULL)
```

Feeling dumb. Sure this was working before. Poked around at it for a while, can't figure out what's changed. Blame `stripe`?

Not a big deal, but maybe worth being aware of?

**Comment by mattaustin** [comment]
Hi,

I just tried setting up the project (clean db) and testing a payment and everything worked as expected - so not sure if this is still a problem?

```
System check identified no issues (0 silenced).
```

I did update the project to use v0.1.3 of thecut-stripe, rather than the git hash.
